version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.17
    - 7.12.18
    - 7.13.0
    - 7.13.1
    - 7.13.17
    - 7.13.3
    - 7.13.4
    - 7.13.6
    - 7.13.8
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.11.0
    - 3.9.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.5
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
